version: '3.1'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data/es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xmx1G -Xms1G"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yaml:ro
    ports:
      - "5601:5601"
    networks:
      - elastic
    environment:
      - SERVER_NAME=kibana
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SERVER_HOST=0.0.0.0
      - LOGGING_QUIET=true
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    user: root
    networks:
      - elastic
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./data/filebeat:/usr/share/filebeat/data
      - /var/log/:/var/log/:ro
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      # Without this filebeat compalains about config file permissions
    command: ["--strict.perms=false"]

  metricbeat:
    image:  docker.elastic.co/beats/metricbeat:7.2.0
    user: root
    networks:
      - elastic
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./data/metricbeat:/usr/share/metricbeat/data
    environment:
      - ELASTICSEARCH_HOST=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    command: ["--strict.perms=false"]

networks:
  elastic:
