version: '2'

services:

  elasticsearch:
    build:
      context: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "127.0.0.1:9200:9200"
    environment:
      ES_JAVA_OPTS: "-Xmx1G -Xms1G"
      ELASTIC_PASSWORD: "$ELASTIC_PASSWORD"
    networks:
      - elastic

  kibana:
    build:
      context: kibana/
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
      SERVER_HOST: "0.0.0.0"
      LOGGING_QUIET: "true"
      ELASTICSEARCH_USERNAME: kibana
      ELASTICSEARCH_PASSWORD: "$ELASTICSEARCH_PASSWORD"

networks:

  elastic:
    driver: bridge
