filebeat.modules:
- module: system
  syslog:
    enabled: true
  auth:
    enabled: true

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST}"]
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}

setup.dashboards:
  enabled: true

setup.kibana:
  host: "${KIBANA_HOST}"
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
